export const TestimonialData = [
  {
    id: 1,
    img: { url: "http://unsplash.it/1000/1000?image=456" },
    title: "Abdullah Alif",
    arrow: "https://img.icons8.com/ios/30/000000/right3.png",
    sun_title: "app developer",
    img_icon: "https://img.icons8.com/ios-glyphs/30/000000/instagram-new.png",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime, qui?",
  },
  {
    id: 2,
    img: { url: "http://unsplash.it/1000/1000?image=434" },
    title: "Towhidul Islam",
    arrow: "https://img.icons8.com/ios/30/000000/right3.png",
    sun_title: "ui ux designer",
    img_icon: "https://img.icons8.com/ios-glyphs/30/000000/phone--v1.png",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime, qui?",
    feature: true,
  },
  {
    id: 3,
    img: { url: "http://unsplash.it/1000/1000?image=452" },
    title: "Niama Akter",
    arrow: "https://img.icons8.com/ios/30/000000/right3.png",
    sun_title: "web developer",
    img_icon: "https://img.icons8.com/ios-glyphs/30/000000/change--v1.png",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime, qui?",
  },
];
